package com.example.commonproject.ai.basicmodel;

import java.util.List;

/**
 * AI모델에서 수신한 응답
 * @param <T>
 */
public interface ModelResponse<T extends ModelResult<?>> {

    /**
     * Retrieves the result of the AI model.
     * @return the result generated by the AI model
     */
    T getResult();

    /**
     * Retrieves the list of generated outputs by the AI model.
     * @return the list of generated outputs
     */
    List<T> getResults();

    /**
     * Retrieves the response metadata associated with the AI model's response.
     * @return the response metadata
     */
//    ResponseMetadata getMetadata();

}
